// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

import {IERC4626} from "@openzeppelin/contracts/interfaces/IERC4626.sol";

/**
 * @title IMeridianVault
 * @notice Interface for Meridian RWA Yield Vaults
 * @dev Extends ERC-4626 with compliance and oracle integration
 */
interface IMeridianVault is IERC4626 {
    // ============================================
    // EVENTS
    // ============================================
    
    event YieldHarvested(uint256 amount, uint256 timestamp);
    event AssetValueUpdated(uint256 oldValue, uint256 newValue, uint256 timestamp);
    event ComplianceStatusChanged(address indexed account, bool status);
    event EmergencyWithdraw(address indexed account, uint256 amount);
    event PerformanceFeeCollected(uint256 amount, address indexed recipient);
    event ManagementFeeCollected(uint256 amount, address indexed recipient);
    event DepositLimitUpdated(uint256 oldLimit, uint256 newLimit);
    event WithdrawRequestCreated(address indexed account, uint256 shares, uint256 requestId);
    event WithdrawRequestProcessed(uint256 requestId, uint256 assets);

    // ============================================
    // ERRORS
    // ============================================
    
    error NotCompliant(address account);
    error DepositLimitExceeded(uint256 requested, uint256 limit);
    error WithdrawLocked(uint256 unlockTime);
    error InsufficientLiquidity(uint256 requested, uint256 available);
    error InvalidOraclePrice();
    error ZeroAmount();
    error InvalidAddress();
    error VaultPaused();
    error NotAuthorized();
    error WithdrawRequestNotReady(uint256 requestId);
    error InvalidWithdrawRequest(uint256 requestId);

    // ============================================
    // STRUCTS
    // ============================================
    
    struct VaultConfig {
        uint256 depositLimit;
        uint256 withdrawLockPeriod;
        uint256 performanceFee; // basis points (100 = 1%)
        uint256 managementFee; // basis points annually
        address feeRecipient;
        address complianceRegistry;
        address priceOracle;
        bool requiresCompliance;
    }

    struct WithdrawRequest {
        address owner;
        uint256 shares;
        uint256 requestTime;
        uint256 minAssets;
        bool processed;
    }

    // ============================================
    // VIEW FUNCTIONS
    // ============================================
    
    /// @notice Returns the vault configuration
    function getConfig() external view returns (VaultConfig memory);
    
    /// @notice Returns if an account is compliant to use this vault
    function isCompliant(address account) external view returns (bool);
    
    /// @notice Returns the total yield generated by the vault
    function totalYieldGenerated() external view returns (uint256);
    
    /// @notice Returns the current APY in basis points
    function currentAPY() external view returns (uint256);
    
    /// @notice Returns the last oracle price update timestamp
    function lastPriceUpdate() external view returns (uint256);
    
    /// @notice Returns pending withdraw request for an account
    function getWithdrawRequest(uint256 requestId) external view returns (WithdrawRequest memory);
    
    /// @notice Returns the available liquidity for immediate withdrawals
    function availableLiquidity() external view returns (uint256);

    // ============================================
    // MUTATIVE FUNCTIONS
    // ============================================
    
    /// @notice Request a withdrawal (for assets with lock periods)
    /// @param shares Amount of shares to withdraw
    /// @param minAssets Minimum assets to receive
    /// @return requestId The ID of the withdrawal request
    function requestWithdraw(uint256 shares, uint256 minAssets) external returns (uint256 requestId);
    
    /// @notice Process a pending withdrawal request
    /// @param requestId The ID of the withdrawal request
    /// @return assets The amount of assets withdrawn
    function processWithdraw(uint256 requestId) external returns (uint256 assets);
    
    /// @notice Harvest yield from underlying RWA
    function harvestYield() external;
    
    /// @notice Update asset value from oracle
    function updateAssetValue() external;
    
    /// @notice Emergency withdraw bypassing normal checks (may incur penalty)
    /// @param shares Amount of shares to withdraw
    /// @return assets Amount of assets received (after penalty)
    function emergencyWithdraw(uint256 shares) external returns (uint256 assets);
}
